namespace Networking
{
	public enum PackageType
	{
		Invalid,
		ConnectionRequest,
		ConnectionResponse,
		ClientShutdown,
		ClientShutdownNotification,
		ChatMessage,
		Ping,
		PingResponse,
		ServerFind,
		ServerFindResponse,
		ServerShutdown,
		TimeSync,
		TimeSyncResponse,
		ActorSync,
		ActorSyncFromServer,
		Ack,
		ClientIDRequest,
		ClientIDResponse,
		SnapshotRequest,
		Snapshot,
		NetworkObjectRequest,
		NetworkObjectSpawn,
		NetworkObjectDestroy,
		NetworkObjectIDAssignement,
		ActorAction
	}
}